# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_auto_20161013_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='group',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
