# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_auto_20161012_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Athlete',
        ),
    ]
